#!/bin/bash
#Author: Connor Harris 23208009

#normalise results


#get the overall word count
word_count=$(grep -w "word" $1 | tr -d 'word ')
sentence_count=$(grep "sentence" euc_cal_1 | tr -d 'sentence ')
words_per_sentence=$(($word_count / $sentence_count))
grep -v "word" euc_cal_1 | grep -v "sentence" | sed 's/[^0-9]*//g' | tr " " "\n" >> words_to_normalise.txt
words_to_normalise_count=$(cat words_to_normalise.txt | wc -l)

for ((i = 1 ; i <= $words_to_normalise_count ; i++)); do 
    current_num=$(head -n $i words_to_normalise.txt | tail -n 1)
    if [[ $current_num > 0 ]] 
    then
        awk "BEGIN {printf \"%.3f\n\", $current_num/$word_count*1000}"
    else 
        echo "0"
    fi
done

rm words_to_normalise.txt
